### ISSUE TITLE
Foreign keys are empty when extracting from preprocessed db

### ISSUE THREAD

**Issue by upjabir** [glee4810/EHRSQL#7]
I run the same command mentioned in readme for preprocessing db. When I try to extract foreign keys from the DB, it gives an empty list, while on the other hand, table.json specifies the foreign key.
![Screenshot 2023-11-08 at 3 38 06 PM](https://github.com/glee4810/EHRSQL/assets/40956091/0248a270-90a2-49bc-a89d-7003aeb47b4f)
Also when I try to get table info, I get information successfully.
![Screenshot 2023-11-08 at 3 38 35 PM](https://github.com/glee4810/EHRSQL/assets/40956091/fa50c43a-d041-49c3-a8a3-e883a870e48c)

**Comment by glee4810** [comment]
We have updated the database schema files (mimic_iii.sql and eicu.sql) and it should work by now. Thanks!
