### ISSUE TITLE
Replicating sqlite database for MIMIC-3 using preprocessing script

### ISSUE THREAD

**Issue by nygim** [glee4810/EHRSQL#9]
Thanks for the great work!

I'm encountering an issue while attempting to create a SQLite database for the MIMIC-3 dataset using the preprocessing script provided in the README.md. After following the instructions, I noticed that the resulting SQLite database seems to be missing some rows present in the train.json and valid.json files.

For instance, when executing the following SQL query on the validation dataset:
```
SELECT labevents.charttime
FROM labevents
WHERE labevents.hadm_id IN (
    SELECT admissions.hadm_id
    FROM admissions
    WHERE admissions.subject_id = 73075
)
AND labevents.itemid IN (
    SELECT d_labitems.itemid
    FROM d_labitems
    WHERE d_labitems.label = 'creatinine'
)
AND datetime(labevents.charttime, 'start of year') = datetime('2105-12-31 23:59:00', 'start of year', '-1 year')
AND strftime('%m', labevents.charttime) = '12'
ORDER BY labevents.valuenum DESC, labevents.charttime ASC
LIMIT 1;
```

I received no results, which seems to be due to the absence of an entry with `admissions.subject_id = 73075` in the admissions table.

Could you please provide guidance or additional steps to ensure the database creation process accurately reflects the data found in the train.json and valid.json files? Thank you so much!

**Comment by glee4810** [comment]
Thank you for pointing this out. I've discovered that the latest update (2 months ago) to the preprocessing code produces a different set of patients. I have reverted this, so please let me know if any further issues arise.
